---
title: "Getting data"
output: html_document
date: "2025-10-24"
---

```{r}
library(Lock5withR)
library(dplyr)
library(ggplot2)
```


```{r}
data(SleepStudy)
head(SleepStudy)
```


```{r}
#filtering to keep variables that we need
filtered_sleepStudy <- SleepStudy %>%
  select(Sex, PoorSleepQuality,LarkOwl, ClassesMissed, GPA)

# spliting up the Lark owl into databse which have only owl, lark or neither
Neither_owl_or_Larks <- filtered_sleepStudy %>%
  filter(LarkOwl == "Neither")
only_owl <- filtered_sleepStudy %>%
  filter(LarkOwl == 'Owl')
only_Lark <- filtered_sleepStudy %>%
  filter(LarkOwl == 'Lark')
```


```{r}
# creating a bar graph to see the sex disruption among each group 
ggplot(Neither_owl_or_Larks, aes(x = Sex)) +
  geom_bar(fill = "skyblue") +
  labs(title = "Count of Neither Owl nor Lark by Sex",
       x = "Sex of Person",
       y = "Count")

ggplot(only_owl, aes(x = Sex)) +
  geom_bar(fill = "skyblue") +
  labs(title = "Count of only Owl by Sex",
       x = "Sex of Person",
       y = "Count")

ggplot(only_Lark, aes(x = Sex)) +
  geom_bar(fill = "skyblue") +
  labs(title = "Count of only Lark by Sex",
       x = "Sex of Person",
       y = "Count")


```

```{r}
#creating a histogram to see distribution of sleep quality 
ggplot(Neither_owl_or_Larks, aes(x = PoorSleepQuality))+
  labs(title = "Count of Neither Owl nor Lark by Sleep Quality",
       x = "Sleep Quality",
       y = "Count") +
  geom_histogram(bins = 15)
ggplot(only_owl, aes(x = PoorSleepQuality))+
   labs(title = "Count of Owl by Sleep Quality",
       x = "Sleep Quality",
       y = "Count") +
  geom_histogram(bins = 15)
ggplot(only_Lark, aes(x = PoorSleepQuality))+
   labs(title = "Count of Lark by Sleep Quality",
       x = "Sleep Quality",
       y = "Count") +
  geom_histogram(bins = 15)
```


```{r}
#scatter plot of sleep quality vs gpa on each group
ggplot(data = Neither_owl_or_Larks, aes(x = PoorSleepQuality, y = GPA)) +
  labs(title = "GPA of Neither Owl nor Lark by Sleep Quality",
       x = "Sleep Quality",
       y = "GPA") +
  geom_point()
ggplot(data = only_owl, aes(x = PoorSleepQuality, y = GPA)) +
  labs(title = "GPA of Owl by Sleep Quality",
       x = "Sleep Quality",
       y = "GPA") +
  geom_point()
ggplot(data = only_Lark, aes(x = PoorSleepQuality, y = GPA)) +
  labs(title = "GPA of Lark by Sleep Quality",
       x = "Sleep Quality",
       y = "GPA") +
  geom_point()

```

```{r}
# box plots of sleep quality vs classes missed divided by sex
ggplot(Neither_owl_or_Larks, aes(x = factor(PoorSleepQuality), y = ClassesMissed, fill = Sex)) +
  geom_boxplot() +
  labs(title = "Distribution of Classes Missed by Sleep Quality and Sex",
       x = "Poor Sleep Quality",
       y = "Classes Missed",
       fill = "Sex")
ggplot(only_owl, aes(x = factor(PoorSleepQuality), y = ClassesMissed, fill = Sex)) +
  geom_boxplot() +
  labs(title = "Distribution of Classes Missed by Sleep Quality and Sex",
       x = "Poor Sleep Quality",
       y = "Classes Missed",
       fill = "Sex")
ggplot(only_Lark, aes(x = factor(PoorSleepQuality), y = ClassesMissed, fill = Sex)) +
  geom_boxplot() +
  labs(title = "Distribution of Classes Missed by Sleep Quality and Sex",
       x = "Poor Sleep Quality",
       y = "Classes Missed",
       fill = "Sex")

```
